<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate("Application Menu Items"); ?> 
					<small><?php echo $this->translate("Page"); ?>: <?php echo $this->page; ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->searchButton("menu-search"); ?>
					
					<?php echo $this->createButton("menu-create"); ?>
				</div>
			</div> 
            <?php if($this->paginator->count() == 0): ?>
			<div class="box-body">
				<div class="alert alert-info">
					<p>
						<i class="fa fa-info-circle" aria-hidden="true"></i> 
						<?php echo $this->translate("No entities found"); ?>
					</p>
				</div>
			</div>
			<?php else: ?>
			
			
			<?php endif; ?>
		</div>
	</div>
</div>