<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate("Application Menu Item"); ?> 
					<small><?php echo $this->entity->getMenuItemName(); ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->deleteButton("menu-item-delete", array("id" => $this->entity->getMenuItemId())); ?>
					
					<?php echo $this->updateButton("menu-item-update", array("id" => $this->entity->getMenuItemId())); ?>
				</div>
			</div>
			<div class="box-body box-profile">
                <h3 class="profile-username text-center">
                	<?php echo $this->entity->getMenuItemName(); ?>
                </h3>
                <p class="text-muted text-center">
                	<?php echo $this->entity->getMenuItemRoute(); ?>
                </p>
                <ul class="list-group list-group-unbordered">
                 <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Item Id"); ?>:</b>
                    	<?php echo $this->entity->getMenuItemId(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Id"); ?>:</b>
                    	<?php echo $this->entity->getMenuId(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Name"); ?>:</b>
                    	<a href="<?php echo $this->url("menu-view", array("id" => $this->entity->getMenuId())); ?>" title="<?php echo $this->translate("View"); ?>">
                    		<?php echo $this->entity->getMenuEntity()->getMenuName(); ?>
                    	</a>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Location"); ?>:</b>
                    	<?php echo $this->entity->getMenuEntity()->getMenuLocation(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Item Name"); ?>:</b>
                    	<?php echo $this->entity->getMenuItemName(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Item Route"); ?>:</b>
                    	<?php echo $this->entity->getMenuItemRoute(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Item Icon"); ?>:</b>
                    	<?php echo $this->entity->getMenuItemIcon(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Item Order"); ?>:</b>
                    	<?php echo $this->entity->getMenuItemOrder(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Menu Item Active"); ?>:</b>
                    	<?php echo ($this->entity->getMenuItemActive() == 1 ? $this->translate("Yes") : $this->translate("No")) ; ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>